# ----------------------------------------------------------------------
# |
# |  validate_with_dependencies.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-07-24 16:25:04
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[callable] Validates v4-DavidBrownell_TheLanguage (and its dependencies)"

on:
  workflow_call:
    inputs:
      repo_branch:                          {type: string, required: true}

jobs:
  _8f219c22-365c-420a-b624-52732e10a76e:
    name: "v4-DavidBrownell_TheLanguage"
    uses: davidbrownell/v4-DavidBrownell_TheLanguage/.github/workflows/validate.yaml@CI-v1
    with:
      repo_branch: "${{ inputs.repo_branch }}"
      bootstrap_branch_overrides: "v4-DavidBrownell_TheLanguage:${{ inputs.repo_branch }}"
