# ----------------------------------------------------------------------
# |
# |  AllErrors.py
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-11-24 12:21:51
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
"""Contains all errors generated by TheLangauge"""

from pathlib import Path

from TheLanguage.Common.Errors import CreateErrorType


# ----------------------------------------------------------------------
