# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         workflows/manual_validate_with_dependencies.jinja2.yaml
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

name: "Validate (including dependencies)"
run-name: "${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}"

on:
  workflow_dispatch:

jobs:
  _2dfa3c47-3baa-4c04-a253-bcd25d2294f8:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-DavidBrownell_TheLanguage/.github/workflows/validate_with_dependencies.yaml@CI-v1
    with:
      repo_branch: "${{ github.ref_name }}"
