name: "Validate"
run-name: "${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      force_setup:                          {type: boolean, required: false, default: false, description: "Apply the '--force' flag during setup activities."}
      force_activate:                       {type: boolean, required: false, default: false, description: "Apply the '--force' flag during activation activities."}
      no_cache:                             {type: boolean, required: false, default: false, description: "Do not use the GitHub action cache for this build."}

jobs:
  _6d4e001d-a366-4e8f-8c31-a8545fada974:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-DavidBrownell_TheLanguage/.github/workflows/validate.yaml@CI-v1
    with:
      repo_branch: "${{ github.ref_name }}"

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}
