# ----------------------------------------------------------------------
# |
# |  validate.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-07-24 16:24:57
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[callable] Validates v4-DavidBrownell_TheLanguage"

on:
  workflow_call:
    inputs:
      repo_branch:                          {type: string, required: true}
      force_setup:                          {type: boolean, required: false, default: false}
      force_activate:                       {type: boolean, required: false, default: false}
      no_cache:                             {type: boolean, required: false, default: false}

      bootstrap_branch_overrides:           {type: string, required: false}

jobs:
  _46f3c68f-5db7-469b-9b86-05592fcea3d5:
    name: "Build and Test"

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        configuration:
          - None

    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_validate.yaml@CI-v1
    with:
      job_name_prefix: "v4-DavidBrownell_TheLanguage"
      is_mixin_repository: False
      repo_name: "davidbrownell/v4-DavidBrownell_TheLanguage"
      repo_branch: "${{ inputs.repo_branch }}"
      bootstrap_branch_overrides: "${{ inputs.bootstrap_branch_overrides }}"

      os: ${{ matrix.os }}
      configuration: ${{ matrix.configuration }}

      run_Builder: true
      run_MatchTests: true

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests: 3
      execute_FunctionalTests: 1
      execute_IntegrationTests: 1
      execute_SystemTests: 1
      execute_LocalEndToEndTests: 1
      execute_EndToEndTests: 0
      execute_BuildVerificationTests: 0
      execute_PerformanceTests: 0
